name: connie
description: Keep your coins together with my 8th remake of an expense manager. Hope this is the final version.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+4

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bson: ^4.0.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true